version: "3.9"
services:
  web:
    container_name: pose-backend
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - ./back-end:/usr/src/app

  apache:
    container_name: pose-frontend
    image: httpd:latest
    ports:
      - "80:80"
    volumes:
    - ./front-end:/usr/local/apache2/htdocs