services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
    - ./front-end:/usr/share/nginx/html
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask

  flask:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./back-end:/usr/src/app