services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 443:443
    volumes:
    - ./front-end:/usr/share/nginx/html
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask

  flask:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    volumes:
      - ./back-end:/usr/src/app